export const BILL_SET_INITIAL_STATE = 'BILL_SET_INITIAL_STATE'

export const BILL_TODAY_CLEAR_ITEM = 'BILL_TODAY_CLEAR_ITEM'
export const BILL_TODAY_SET_ITEM = 'BILL_TODAY_SET_ITEM'

export const BILL_SET_CRITERIA = 'BILL_SET_CRITERIA'

export const BILL_TODAY_CLEAR_LIST_ITEMS = 'BILL_TODAY_CLEAR_LIST_ITEMS'
export const BILL_TODAY_GET_LIST_ITEMS = 'BILL_TODAY_GET_LIST_ITEMS'
export const BILL_TODAY_GET_LIST_ITEMS_SUCCESS = 'BILL_TODAY_GET_LIST_ITEMS_SUCCESS'
export const BILL_TODAY_GET_LIST_ITEMS_FAIL = 'BILL_TODAY_GET_LIST_ITEMS_FAIL'

export const BILL_CLEAR_LIST_ITEMS = 'BILL_CLEAR_LIST_ITEMS'
export const BILL_SEARCH_LIST_ITEMS = 'BILL_SEARCH_LIST_ITEMS'
export const BILL_SEARCH_LIST_ITEMS_SUCCESS = 'BILL_SEARCH_LIST_ITEMS_SUCCESS'
export const BILL_SEARCH_LIST_ITEMS_FAIL = 'BILL_SEARCH_LIST_ITEMS_FAIL'

export const BILL_SET_ERROR = 'BILL_SET_ERROR'