export const CAMPAIGN_TYPE_INITIAL_STATE = 'CAMPAIGN_TYPE_INITIAL_STATE'
export const CAMPAIGN_TYPE_SEARCH_LIST = 'CAMPAIGN_TYPE_SEARCH_LIST'
export const CAMPAIGN_TYPE_SEARCH_LIST_SUCCESS = 'CAMPAIGN_TYPE_SEARCH_LIST_SUCCESS'
export const CAMPAIGN_TYPE_SEARCH_LIST_FAIL = 'CAMPAIGN_TYPE_SEARCH_LIST_FAIL'

export const CAMPAIGN_TYPE_SET_ITEM = 'CAMPAIGN_TYPE_SET_ITEM'
