export const CHECK_IN_SET_INITIAL_STATE = 'CHECK_IN_SET_INITIAL_STATE'
export const CHECK_IN_ADD_PHOTO = 'CHECK_IN_ADD_PHOTO'
export const CHECK_IN_SET_IS_SUBMIT = 'CHECK_IN_SET_IS_SUBMIT'

export const CHECK_IN_SUBMIT = 'CHECK_IN_SUBMIT'
export const CHECK_IN_SUBMIT_SUCCESS = 'CHECK_IN_SUBMIT_SUCCESS'
export const CHECK_IN_SUBMIT_FAIL = 'CHECK_IN_SUBMIT_FAIL'

export const CHECK_IN_SET_IS_LOADING = 'CHECK_IN_SET_IS_LOADING'
