export const CUSTOMER_SET_INITIAL_STATE = 'CUSTOMER_SET_INITIAL_STATE';
export const CUSTOMER_CLEAR_LIST = 'CUSTOMER_CLEAR_LIST';
export const CUSTOMER_SEARCH_LIST = 'CUSTOMER_SEARCH_LIST';
export const CUSTOMER_SEARCH_LIST_SUCCESS = 'CUSTOMER_SEARCH_LIST_SUCCESS';
export const CUSTOMER_SEARCH_LIST_FAIL = 'CUSTOMER_SEARCH_LIST_FAIL';

export const CUSTOMER_SET_ITEM_INFO = 'CUSTOMER_SET_ITEM_INFO';
export const CUSTOMER_SET_ITEM_CUS_ADDB = 'CUSTOMER_SET_ITEM_CUS_ADDB';
export const CUSTOMER_SET_ITEM_LST_VISIT_DOC =
  'CUSTOMER_SET_ITEM_LST_VISIT_DOC';
export const CUSTOMER_SET_ITEM_LST_BILL_DOC = 'CUSTOMER_SET_ITEM_LST_BILL_DOC';
export const CUSTOMER_SET_ITEM_CUS_PAY_INF = 'CUSTOMER_SET_ITEM_CUS_PAY_INF';
export const CUSTOMER_SET_ITEM_CREDIT_LIM = 'CUSTOMER_SET_ITEM_CREDIT_LIM';
export const CUSTOMER_SET_ITEM_ARCONDITION = 'CUSTOMER_SET_ITEM_ARCONDITION';
export const CUSTOMER_SET_ITEM_TEMP_CUS = 'CUSTOMER_SET_ITEM_TEMP_CUS';
export const CUSTOMER_SET_ARSUMMARY = 'CUSTOMER_SET_ARSUMMARY';
export const CUSTOMER_SET_ARPRB = 'CUSTOMER_SET_ARPRB';

export const CUSTOMER_SET_CRITERIA = 'CUSTOMER_SET_CRITERIA';
export const CUSTOMER_SET_KEYWORD = 'CUSTOMER_SET_KEYWORD';

export const CUSTOMER_SET_ERROR = 'CUSTOMER_SET_ERROR';

export const CUSTOMER_SEARCH_NEAR_BY = 'CUSTOMER_SEARCH_NEAR_BY';
export const CUSTOMER_SEARCH_NEAR_BY_SUCCESS =
  'CUSTOMER_SEARCH_NEAR_BY_SUCCESS';
export const CUSTOMER_SEARCH_NEAR_BY_FAIL = 'CUSTOMER_SEARCH_NEAR_BY_FAIL';

export const CUSTOMER_GET_AR_LINE = 'CUSTOMER_GET_AR_LINE';
export const CUSTOMER_GET_AR_LINE_SUCCESS = 'CUSTOMER_GET_AR_LINE_SUCCESS';
export const CUSTOMER_GET_AR_LINE_FAIL = 'CUSTOMER_GET_AR_LINE_FAIL';

export const CUSTOMER_GET_AR_PRICE_TAB_SUCCESS =
  'CUSTOMER_GET_AR_PRICE_TAB_SUCCESS';
export const CUSTOMER_GET_AR_PRICE_TAB_FAIL = 'CUSTOMER_GET_AR_PRICE_TAB_FAIL';
