export const CUSTOMER_SELECT_SET_SELECTED = 'CUSTOMER_SELECT_SET_SELECTED';
export const CUSTOMER_SELECT_FETCH_DUE_DATE_REQUEST =
  'CUSTOMER_SELECT_FETCH_DUE_DATE_REQUEST';
export const CUSTOMER_SELECT_FETCH_DUE_DATE_SUCCESS =
  'CUSTOMER_SELECT_FETCH_DUE_DATE_SUCCESS';
export const CUSTOMER_SELECT_FETCH_DUE_DATE_FAIL =
  'CUSTOMER_SELECT_FETCH_DUE_DATE_FAIL';
export const CUSTOMER_SELECT_SET_DUE_DATE = 'CUSTOMER_SELECT_SET_DUE_DATE';
export const CUSTOMER_SELECT_CLEAR = 'CUSTOMER_SELECT_CLEAR';
