export const CUSTOMER_TYPE_SET_INITIAL_STATE = 'CUSTOMER_TYPE_SET_INITIAL_STATE'
export const CUSTOMER_TYPE_CLEAR_ITEM = 'CUSTOMER_TYPE_CLEAR_ITEM'

export const CUSTOMER_TYPE_SEARCH_LIST = 'CUSTOMER_TYPE_SEARCH_LIST'
export const CUSTOMER_TYPE_SEARCH_LIST_SUCCESS = 'CUSTOMER_TYPE_SEARCH_LIST_SUCCESS'
export const CUSTOMER_TYPE_SEARCH_LIST_FAIL = 'CUSTOMER_TYPE_SEARCH_LIST_FAIL'

export const CUSTOMER_TYPE_SET_ITEM = 'CUSTOMER_TYPE_SET_ITEM'

export const CUSTOMER_TYPE_SET_KEYWORD = 'CUSTOMER_TYPE_SET_KEYWORD'
export const CUSTOMER_TYPE_SET_CRITERIA = 'CUSTOMER_TYPE_SET_CRITERIA'

export const CUSTOMER_TYPE_CLEAR_LIST = 'CUSTOMER_TYPE_CLEAR_LIST'

export const CUSTOMER_TYPE_SET_IS_ERROR = 'CUSTOMER_TYPE_SET_IS_ERROR'
