export const DROP_POINT_SET_INITIAL_STATE = 'DROP_POINT_SET_INITIAL_STATE'

export const DROP_POINT_CLEAR_LIST_ITEMS = 'DROP_POINT_CLEAR_LIST_ITEMS'
export const DROP_POINT_GET_LIST_ITEMS = 'DROP_POINT_GET_LIST_ITEMS'
export const DROP_POINT_GET_LIST_ITEMS_SUCCESS = 'DROP_POINT_GET_LIST_ITEMS_SUCCESS'
export const DROP_POINT_GET_LIST_ITEMS_FAIL = 'DROP_POINT_GET_LIST_ITEMS_FAIL'

export const DROP_POINT_SET_IS_LOADING = 'DROP_POINT_SET_IS_LOADING'
export const DROP_POINT_SET_IS_ERROR = 'DROP_POINT_SET_IS_ERROR'

export const DROP_POINT_SEARCH_LIST_ITEMS = 'DROP_POINT_SEARCH_LIST_ITEMS'
export const DROP_POINT_SEARCH_LIST_ITEMS_SUCCESS = 'DROP_POINT_SEARCH_LIST_ITEMS_SUCCESS'
export const DROP_POINT_SEARCH_LIST_ITEMS_FAIL = 'DROP_POINT_SEARCH_LIST_ITEMS_FAIL'