export const MILE_SET_INITIAL_STATE = 'MILE_SET_INITIAL_STATE'
export const MILE_ADD_PHOTO = 'MILE_ADD_PHOTO'
export const MILE_SET_MILEAGE = 'MILE_SET_MILEAGE'
export const MILE_SET_IS_SUBMIT = 'MILE_SET_IS_SUBMIT'

export const MILE_SUBMIT = 'MILE_SUBMIT'
export const MILE_SUBMIT_SUCCESS = 'MILE_SUBMIT_SUCCESS'
export const MILE_SUBMIT_FAIL = 'MILE_SUBMIT_FAIL'

export const MILE_SET_IS_LOADING = 'MILE_SET_IS_LOADING'
