export const ORDER_SET_INITIAL_STATE = 'ORDER_SET_INITIAL_STATE';

export const ORDER_SET_IS_NOT_FOUND = 'ORDER_SET_IS_NOT_FOUND';
export const ORDER_SET_IS_LOADING = 'ORDER_SET_IS_LOADING';
export const ORDER_SET_IS_ERROR_MESSAGE = 'ORDER_SET_IS_ERROR_MESSAGE';

export const ORDER_SET_HEADER = 'ORDER_SET_HEADER';
export const ORDER_REMOVE_ALL_PRODUCT_ITEMS = 'ORDER_REMOVE_ALL_PRODUCT_ITEMS';

export const ORDER_ADD_PRODUCT_ITEM = 'ORDER_ADD_PRODUCT_ITEM';
export const ORDER_ADD_PRODUCT_ITEMS = 'ORDER_ADD_PRODUCT_ITEMS';
export const ORDER_EDIT_PRODUCT_ITEM = 'ORDER_EDIT_PRODUCT_ITEM';
export const ORDER_REMOVE_PRODUCT_ITEM = 'ORDER_REMOVE_PRODUCT_ITEM';

export const ORDER_SET_SWIPE_CURENT = 'ORDER_SET_SWIPE_CURENT';
export const ORDER_PUSH_SWIPE_LIST = 'ORDER_PUSH_SWIPE_LIST';
export const ORDER_REMOVE_ALL_SWIPE_LIST = 'ORDER_REMOVE_ALL_SWIPE_LIST';

export const ORDER_SET_VDI_REMARK = 'ORDER_SET_VDI_REMARK';

export const ORDER_SET_DIS_BILL1 = 'ORDER_SET_DIS_BILL1';
export const ORDER_SET_DIS_BILL2 = 'ORDER_SET_DIS_BILL2';
export const ORDER_SET_DIS_BILL1_AFTER_DISCOUNT = 'ORDER_SET_DIS_BILL1_AFTER_DISCOUNT';
export const ORDER_SET_DIS_BILL2_AFTER_DISCOUNT = 'ORDER_SET_DIS_BILL2_AFTER_DISCOUNT';
export const ORDER_SET_DIS_COUNT_TYPE1 = 'ORDER_SET_DIS_COUNT_TYPE1';
export const ORDER_SET_DIS_COUNT_TYPE2 = 'ORDER_SET_DIS_COUNT_TYPE2';

export const ORDER_SET_DIS_BILL_PROCESS = 'ORDER_SET_DIS_BILL_PROCESS';
export const ORDER_SET_HEADER_PROCESSED_SHIP_DATE =
  'ORDER_SET_HEADER_PROCESSED_SHIP_DATE';
export const ORDER_CLEAR_DIS_BILL = 'ORDER_CLEAR_DIS_BILL';

export const ORDER_CALCULATE_PRODUCT_SUMMARY =
  'ORDER_CALCULATE_PRODUCT_SUMMARY';
export const ORDER_CALCULATE_PRODUCT_PROCESSED_SUMMARY =
  'ORDER_CALCULATE_PRODUCT_PROCESSED_SUMMARY';
export const ORDER_CALCULATE_NET_PRICE_AFTER_DISCOUNT =
  'ORDER_CALCULATE_NET_PRICE_AFTER_DISCOUNT';

export const ORDER_ADD_VISIT_IMAGE_ITEM = 'ORDER_ADD_VISIT_IMAGE_ITEM';
export const ORDER_REMOVE_VISIT_IMAGE_ITEM = 'ORDER_REMOVE_VISIT_IMAGE_ITEM';
export const ORDER_REMOVE_ALL_VISIT_IMAGE_ITEMS =
  'ORDER_REMOVE_ALL_VISIT_IMAGE_ITEMS';

export const ORDER_ADD_STOCK_IMAGE_ITEM = 'ORDER_ADD_STOCK_IMAGE_ITEM';
export const ORDER_REMOVE_STOCK_IMAGE_ITEM = 'ORDER_REMOVE_STOCK_IMAGE_ITEM';
export const ORDER_REMOVE_ALL_STOCK_IMAGE_ITEMS =
  'ORDER_REMOVE_ALL_STOCK_IMAGE_ITEMS';

export const ORDER_PROCESS = 'ORDER_SUBMIT';
export const ORDER_PROCESS_SUCCESS = 'ORDER_SUBMIT_SUCCESS';
export const ORDER_PROCESS_FAIL = 'ORDER_SUBMIT_FAIL';

export const ORDER_CREATE = 'ORDER_CREATE';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';

export const ORDER_SET_HEADER_PROCESSED = 'ORDER_SET_HEADER_PROCESSED';
export const ORDER_SET_ITEMS_PROCESSED = 'ORDER_SET_ITEMS_PROCESSED';
export const ORDER_SET_ITEMS_PRT_PROCESSED = 'ORDER_SET_ITEMS_PRT_PROCESSED';
export const ORDER_SET_ITEMS = 'ORDER_SET_ITEMS';

export const ORDER_GET_PRODUCT_LIST_FROM_LAST_BILL_BY_AR_CODE =
  'ORDER_GET_PRODUCT_LIST_FROM_LAST_BILL_BY_AR_CODE';
export const ORDER_GET_PRODUCT_LIST_FROM_LAST_BILL_BY_AR_CODE_SUCCESS =
  'ORDER_GET_PRODUCT_LIST_FROM_LAST_BILL_BY_AR_CODE_SUCCESS';
export const ORDER_GET_PRODUCT_LIST_FROM_LAST_BILL_BY_AR_CODE_FAIL =
  'ORDER_GET_PRODUCT_LIST_FROM_LAST_BILL_BY_AR_CODE_FAIL';

export const ORDER_SET_HEADER_PROCESSED_VDI_CHEQUE_DATE =
  'ORDER_SET_HEADER_PROCESSED_VDI_CHEQUE_DATE';
export const ORDER_SET_HEADER_PROCESSED_VDI_CHEQUE_BANK =
  'ORDER_SET_HEADER_PROCESSED_VDI_CHEQUE_BANK';
export const ORDER_SET_HEADER_PROCESSED_VDI_CHEQUE_NO =
  'ORDER_SET_HEADER_PROCESSED_VDI_CHEQUE_NO';
export const ORDER_SET_HEADER_PROCESSED_VDI_BANK_TRANSFER =
  'ORDER_SET_HEADER_PROCESSED_VDI_BANK_TRANSFER';
export const ORDER_SET_HEADER_PROCESSED_VDI_QR_REFER =
  'ORDER_SET_HEADER_PROCESSED_VDI_QR_REFER';

export const ORDER_SURVEY_SET_VDI_ANS = 'ORDER_SURVEY_SET_VDI_ANS';

export const ORDER_VISIT_SET_VDI_VISIT = 'ORDER_VISIT_SET_VDI_VISIT';
export const ORDER_SET_HEADER_VDI_USER_REF = 'ORDER_SET_HEADER_VDI_USER_REF';
