export const PRODUCT_SKU_ALT_SET_INITIAL_STATE = 'PRODUCT_SKU_ALT_SET_INITIAL_STATE'
export const PRODUCT_SKU_ALT_CLEAR_ITEM = 'PRODUCT_SKU_ALT_CLEAR_ITEM'

export const PRODUCT_SKU_ALT_SEARCH_LIST = 'PRODUCT_SKU_ALT_SEARCH_LIST'
export const PRODUCT_SKU_ALT_SEARCH_LIST_SUCCESS = 'PRODUCT_SKU_ALT_SEARCH_LIST_SUCCESS'
export const PRODUCT_SKU_ALT_SEARCH_LIST_FAIL = 'PRODUCT_SKU_ALT_SEARCH_LIST_FAIL'

export const PRODUCT_SKU_ALT_SET_ITEM = 'PRODUCT_SKU_ALT_SET_ITEM'

export const PRODUCT_SKU_ALT_SET_KEYWORD = 'PRODUCT_SKU_ALT_SET_KEYWORD'
export const PRODUCT_SKU_ALT_SET_CRITERIA = 'PRODUCT_SKU_ALT_SET_CRITERIA'

export const PRODUCT_SKU_ALT_CLEAR_LIST = 'PRODUCT_SKU_ALT_CLEAR_LIST'
