export const PRODUCT_SET_INITIAL_STATE = 'PRODUCT_SET_INITIAL_STATE'
export const PRODUCT_SET_INITIAL_STATE_IGNORE_MODAL = 'PRODUCT_SET_INITIAL_STATE_IGNORE_MODAL'
export const PRODUCT_CLEAR_ITEM = 'PRODUCT_CLEAR_ITEM'

export const PRODUCT_SEARCH_LIST = 'PRODUCT_SEARCH_LIST'
export const PRODUCT_SEARCH_LIST_SUCCESS = 'PRODUCT_SEARCH_LIST_SUCCESS'
export const PRODUCT_SEARCH_LIST_FAIL = 'PRODUCT_SEARCH_LIST_FAIL'

export const PRODUCT_GET_CATEGORY_LIST = 'PRODUCT_GET_CATEGORY_LIST'
export const PRODUCT_GET_CATEGORY_LIST_SUCCESS = 'PRODUCT_GET_CATEGORY_LIST_SUCCESS'
export const PRODUCT_GET_CATEGORY_LIST_FAIL = 'PRODUCT_GET_CATEGORY_LIST_FAIL'

export const PRODUCT_SET_ITEM = 'PRODUCT_SET_ITEM'

export const PRODUCT_SET_ITEM_QTY = 'PRODUCT_SET_ITEM_QTY'
export const PRODUCT_SET_ITEM_TOTAL_PRICE = 'PRODUCT_SET_ITEM_TOTAL_PRICE'
export const PRODUCT_SET_ITEM_NET_PRICE = 'PRODUCT_SET_ITEM_NET_PRICE'
export const PRODUCT_SET_ITEM_DISCOUNT = 'PRODUCT_SET_ITEM_DISCOUNT'
export const PRODUCT_SET_ITEM_TOTAL_DISCOUNT = 'PRODUCT_SET_ITEM_TOTAL_DISCOUNT'
export const PRODUCT_SET_ITEM_FREE = 'PRODUCT_SET_ITEM_FREE'
export const PRODUCT_SET_ITEM_LOT = 'PRODUCT_SET_ITEM_LOT'
export const PRODUCT_SET_ITEM_SERIAL = 'PRODUCT_SET_ITEM_SERIAL'

export const PRODUCT_SET_CRITERIA = 'PRODUCT_SET_CRITERIA'
export const PRODUCT_SET_KEYWORD = 'PRODUCT_SET_KEYWORD'
export const PRODUCT_SET_CRITERIA_GOODS_CODE = 'PRODUCT_SET_CRITERIA_GOODS_CODE'
export const PRODUCT_SET_MODAL = 'PRODUCT_SET_MODAL'

export const PRODUCT_CLEAR_LIST = 'PRODUCT_CLEAR_LIST'

export const PRODUCT_SET_ERROR = 'PRODUCT_SET_ERROR'

export const PRODUCT_SKU_ALT_SEARCH_LIST = 'PRODUCT_SKU_ALT_SEARCH_LIST'
export const PRODUCT_SKU_ALT_SEARCH_LIST_SUCCESS = 'PRODUCT_SKU_ALT_SEARCH_LIST_SUCCESS'
export const PRODUCT_SKU_ALT_SEARCH_LIST_FAIL = 'PRODUCT_SKU_ALT_SEARCH_LIST_FAIL'

export const PRODUCT_SET_SCR_LIST_ITEMS = 'PRODUCT_SET_SCR_LIST_ITEMS'

export const PRODUCT_ADD_OR_EDIT_SCR_CHOOSE_ITEMS = 'PRODUCT_ADD_OR_EDIT_SCR_CHOOSE_ITEMS'
export const PRODUCT_REMOVE_SCR_PICK_ITEMS = 'PRODUCT_REMOVE_SCR_PICK_ITEMS'

export const PRODUCT_SET_DISABLED_BUTTON = 'PRODUCT_SET_DISABLED_BUTTON'

export const PRODUCT_SEARCH_BY_SKU_ALT_LIST_SUCCESS = 'PRODUCT_SEARCH_BY_SKU_ALT_LIST_SUCCESS'

export const PRODUCT_SET_LIST_ITEMS = 'PRODUCT_SET_LIST_ITEMS'


