export const REPORT_SET_INITIAL_STATE = 'REPORT_SET_INITIAL_STATE'
export const REPORT_SALE_SET_INITIAL_STATE = 'REPORT_SALE_SET_INITIAL_STATE'
export const REPORT_SALE_GET_ITEM = 'REPORT_SALE_GET_ITEM'
export const REPORT_SALE_GET_ITEM_SUCCESS = 'REPORT_SALE_GET_ITEM_SUCCESS'
export const REPORT_SALE_GET_ITEM_FAIL = 'REPORT_SALE_GET_ITEM_FAIL'

export const REPORT_SET_IS_LOADING = 'REPORT_SET_IS_LOADING'
export const REPORT_SET_DATE = 'REPORT_SET_DATE'
export const REPORT_SET_IS_ERROR = 'REPORT_SET_IS_ERROR'
export const REPORT_SET_ERROR_MESSAGE = 'REPORT_SET_ERROR_MESSAGE'

export const REPORT_GET_DATA = 'REPORT_GET_DATA'
export const REPORT_GET_DATA_SUCCESS = 'REPORT_GET_DATA_SUCCESS'
export const REPORT_GET_DATA_FAIL = 'REPORT_GET_DATA_FAIL'


export const GET_REPORT_NAME = 'GET_REPORT_NAME'
export const GET_REPORT_NAME_SUCCESS = 'GET_REPORT_NAME_SUCCESS'
export const GET_REPORT_NAME_FAIL = 'GET_REPORT_NAME_FAIL'

export const GET_PRINT_REPORT = 'GET_PRINT_REPORT'
export const GET_PRINT_REPORT_SUCCESS = 'GET_PRINT_REPORT_SUCCESS'
export const GET_PRINT_REPORT_FAIL = 'GET_PRINT_REPORT_FAIL'

export const GET_PRINT_STATUS = 'GET_PRINT_STATUS'
export const GET_PRINT_STATUS_SUCCESS = 'GET_PRINT_STATUS_SUCCESS'
export const GET_PRINT_STATUS_FAIL = 'GET_PRINT_STATUS_FAIL'

export const GET_DOWNLOAD_SUCCESS = 'GET_DOWNLOAD_SUCCESS'

export const SET_SETTING_ERP = 'SET_SETTING_ERP'